export * from './matches.service';
import { MatchesService } from './matches.service';
export * from './tippers.service';
import { TippersService } from './tippers.service';
export * from './tipps.service';
import { TippsService } from './tipps.service';
export * from './tipsAdmin.service';
import { TipsAdminService } from './tipsAdmin.service';
export * from './values.service';
import { ValuesService } from './values.service';
export const APIS = [MatchesService, TippersService, TippsService, TipsAdminService, ValuesService];
